### ISSUE TITLE
مشکل آپلود 99 درصد

### ISSUE THREAD

**Issue by oAwake** [IRMilad/rubika#2]
سلام دادا خوبی؟
فقط بگو از کجا پایتون یاد گرفتی خیلی محشره 
ولی خوب آپلودرت دانلودش درسته 
اما آپلودش تا 99 درصد میره ولی خوب از اون دیگه بیشتر نمیشه
گمونم میتونه مال request_file باشه

**Comment by mivmi** [comment]
سلام ، 
بررسی کردم مشکلی نداشت ممنون میشم خطایی که میده رو بدی
