### ISSUE TITLE
داکیومنت

### ISSUE THREAD

**Issue by Mahdikhoubrouy** [IRMilad/rubika#3]
سلام لطفا یه داکیومنت هرچه سریعتر اضافه کنید ممنون 

**و اینکه واقعا کتابخونه کاربردی و خفنی زدی دمت گرم**

**Comment by mivmi** [comment]
سلام، نسخه بتا هست و صرفا برای این که کارتون راه بیفته گذاشتمش

توی وقت آزادم دارم روش کار میکنم که نسخه اصلی تموم بشه اون موقعه مستندات هم تکمیل میکنم
