### ISSUE TITLE
asynchronous

### ISSUE THREAD

**Issue by oAwake** [IRMilad/rubika#4]
داداش کتابخونت عالیه خیلی خوب اما یه مشکلی هست این که نمیتونه تا هندل پیام قبلی تموم نشده پیام جدید بگیره 
و همزمان نیست هرچی تحقیق کردم چیز درستی برای همزمانی با async پیدا نکردم 

اگه میشه ورژن بعد رو یه جوری با threading ببر جلو

**Comment by mivmi** [comment]
سلام ممنون بابت گزارش، کتابخونه رو اپدیت کنید مشکل برطرف شد

[برای ایجاد تسک ](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task)

**Comment by oAwake** [comment]
اوکی ممنون فقط مطمئن هستید وقتی مثلا یه پیام بیاد تو سوکت اینو بزنم تا هندل شه پیام بعد قبل از هندل شدن اون میاد؟

**Comment by mivmi** [comment]
بله، پیام ها دیگه توی صف صبر نمیکنه

تست کنید نتیجه رو بگید

**Comment by sajjadsoleimani** [comment]
حتما ولی خوب از این createtask قبلا استفاده کرده بودم بسیار رم وسی پی یو‌ زیادی میبرد وسیستم رو تا مرز کرش برد
البته شاید کذ من بهینه نبوده

**Comment by oAwake** [comment]
متاسفانه مشکل حل نشده
![image](https://user-images.githubusercontent.com/80032860/185410199-0f682a49-cba4-4749-a9d7-eaa9dd7659e0.png)

این هم کدها همینطور که میبنید کتابخونه شما رو بغل پروژه گذاشتم 
دو تا پیام داخل پیام های ذخیره شده فرستادم
پیام 1 رو داد اما پیام دو رو 520 ثانیه بعد داد 
البته این مثاله در صورتی که باید پیام رو همون لحظه بده و هندلشون همزمان باشه امام اینچنین نبود

**Comment by mivmi** [comment]
گمونم شما هنوز با async اشنا نیستید، time.sleep باعث فریز شدن کل برنامه میشه توی async

بجای اون از 
asyncio.sleep
 استفاده کنید ، توجه داشته باشین هر کتابخونه ای که داخل کد استفاده میکنید async باشه مثلا بجای requests از aiohttp استفاده کنید و ...

**Comment by oAwake** [comment]
اها مثلا برای open کردن فایل هم باید 
async with open
استفاده کرد؟

**Comment by mivmi** [comment]
نه ، میتونید از aiofiles استفاده کنید ولی از open هم استفاده کنید مشکلی درست نمیشه
