### ISSUE TITLE
فعالسازی با auth

### ISSUE THREAD

**Issue by oAwake** [IRMilad/rubika#5]
سلام 
فعالسازی کتابخونه فقط با فایل که خودش میسازه قابل انجام هست و با auth نمیشه 

اگه مشکلی نیست یه قابلیت اضافه بشه که هم با auth کار کنه و هم با فایل 

همچنین string session رو هم امتحان کردم اما گویا با string session باگی داره و کار نمیکنه

**Comment by mivmi** [comment]
سلام،

یکی از اشتباهاتی که میکنید استفاده از auth در یه دیوایس دیگه (ربات) هست

که ممکنه باعث بن شدن اکانت یا باطل شدن auth بشه ولی خب برای ساخت سیشن با auth میتونید فایل SqliteSession رو بخونید 

لطفا ارور مربوط به string session هم بدید

**Comment by oAwake** [comment]
با string session که میرم میگه not registered اما همون auth رو تبدیل به sqlite session میکنم کار میکنه

**Comment by oAwake** [comment]
چون من یه پروژه داشتم که با auth های مختلف کار میکنه و اکانت های زیاد که میخواستم بتونم هر لحظه چینج کنم اما باید یه فایل بسازم برای هر کدوم که چون تعداد auth ها زیاده حافظه سرور پر میشه

چیز خاصی ندارن auth ها همون authو user agent و کلاینت 
هستن 

که خوب تو این پروژه به حز auth اون دو تا ثابتن

**Comment by oAwake** [comment]
چون روبیکا زیاد هوشمند نیست در حالحاضر حتی اگر auth کلاینتش اشتباه باشه یا user agent بازم کار میکنه

**Comment by mivmi** [comment]
هدف ما استفاده از باگ های روبیکا نیست، باید طبق چهارچوب قوانین پیش بریم
