### ISSUE TITLE
مشکل except با exception ها

### ISSUE THREAD

**Issue by oAwake** [IRMilad/rubika#6]
![image](https://user-images.githubusercontent.com/80032860/185644229-61ad25c7-373f-4614-a273-c3e3d3cfe635.png)

ببخشید هی مزاحم میشم ها 
اما کتابخونه هم ارور ها رو از نوع client error میشناسه و نمیشه از except به راحتی استفاده کرد

**Comment by mivmi** [comment]
این مشکلات و سوالات شما مربوط به پایتون هست, این خطا وقتی رخ میده که دسترسی نداشته باشی

```python
try:
   #your code ...

except exceptions.InvalidAuth as err:
    print(err)
```
